name: omsobliga
description: Blogging about stuffs
meta_description: "Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://omsobliga.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://omsobliga.github.io"
author: "omsobliga"

# Disqus config
disqus-shortname: ""
